### ISSUE TITLE
Spinbox widget breaks when I use backspace to delete all its contents

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#58] opened 2022-09-29 13:21 UTC
Hi thanks a lot for this fantastic project, I've been learning to use it, and I really like it.

Recently I hit below error when I using a SpinBox and want to correct the actual value myself and set manually.

Let's say spinbox, shows 500 as value and I wanted to set it to 1, or any other number, when you use back space key there, all is ok if you DO NOT delete all text(numbers) in there, when you delete last digit then this happens:

```
Traceback (most recent call last):
  File "/Users/larrycastro/Documents/workspace/lab-constructor/./lab-constructor.py", line 1960, in <module>
    tui_menu()
  File "/Users/larrycastro/Documents/workspace/lab-constructor/./lab-constructor.py", line 1884, in tui_menu
    rootWindow.mainloop()
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 113, in mainloop
    self._mainLoop()
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 122, in _mainLoop
    self._input.start()
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 77, in start
    self.key_process(stdinRead)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/TTkTerm/input.py", line 155, in key_process
    self.inputEvent.emit(kevt, mevt)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 123, in emit
    slot(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 128, in _processInput
    self._key_event(kevt)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/ttk.py", line 188, in _key_event
    keyHandled = focusWidget.keyEvent(kevt)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkWidgets/spinbox.py", line 84, in keyEvent
    return TTkLineEdit.keyEvent(self._lineEdit, evt)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkWidgets/lineedit.py", line 233, in keyEvent
    self.textEdited.emit(self._text)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkCore/signal.py", line 123, in emit
    slot(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/TermTk/TTkWidgets/spinbox.py", line 73, in _textEdited
    self.setValue(int(text))
ValueError: invalid literal for int() with base 10: ''
```

I'm thinking to do a workaround at the `valueChanged` to catch all there and prevent this exception... not sure if this can work..,

I also think this is a bug, because I just tried on your online sandbox, and I think it breaks (https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html) widgets at spinxbox field example.

Please let me know if you need any ohter info from me.
Regards

**Comment by ceccopierangiolieugenio** [comment] 2022-09-29 18:26
Looking at this now,
Thanks for highlighting it.

**Comment by ceccopierangiolieugenio** [comment] 2022-09-29 19:13
Fixed in: https://github.com/ceccopierangiolieugenio/pyTermTk/commit/13fcdf7a1522659bcd9ad2fa3438f9153af6562f
I will release it soon.
Thanks.

**Comment by ceccopierangiolieugenio** [comment] 2022-09-29 21:22
Fix deployed in
pyTermTk **0.12.1a4**

**Comment by castben** [comment] 2022-09-30 08:35
Hi again,

This is crazy, thank you for taking care of this issue so quickly!, I will test it out and will let you know 
Thank you very much!
Regards,

**Comment by ceccopierangiolieugenio** [comment] 2022-09-30 14:13
I am trying to reproduce the issue but I can't,
would you be able to share your code?
or any slice that can reproduce this issue?

**Comment by castben** [comment] 2022-09-30 16:54
Hi @ceccopierangiolieugenio, 

I do apologize!, I'm sorry I found issue. it was totally my fault!

How i discovered this issue:
1) I've recreated a simple frame and window, then added spinbox... it worked perfectly no defects at all...
2) Add few pieces of my code... 
3) and the problem popped up... then sneaked into the code, and found the culprit:
```    
    @pyTTkSlot()
    def spinbox_value(self, value=None):
        """

        :param value:
        :return:
        """
        print(value)                                 <----------------- here is it!
        if value == '':
            return 0```

Do you remember I was trying to setup this to find out if I was able to capture  exception (which I was ovbiusly wrong) because it will break anyway without your changes.

then I totally forgot to get rid of this...

I'm sorry for waste your time. 

You can consider this bug fixed. Thank you for your patience and fast fix.

**Comment by ceccopierangiolieugenio** [comment] 2022-09-30 17:22
heheh, no worries,

Actually I was wondering if you used something like copy and paste to change the value
since I think that some widgets are still not protected from ANSI escape codes or control chars i.e. "\t" "\n".

Thanks

**Closed by ceccopierangiolieugenio** 2022-09-30 17:22 UTC
